import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", ".dark"],
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/pages/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/features/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        neutral: {
          25: "#FDFDFD",
          50: "#FAFAFA",
          100: "#F5F5F5",
          200: "#E9EAEB",
          300: "#D5D7DA",
          400: "#A4A7AE",
          500: "#717680",
          600: "#535862",
          700: "#414651",
          800: "#252B37",
          900: "#181D27",
          950: "#0A0D12",
        },
        primary: {
          100: "#F6F9FE",
          200: "#7751F9",
          300: "#6936F2",
        },
        accent: {
          red: "#D9206E",
          green: "#079455",
          yellow: "#FBD022",
        },
      },
      fontSize: {
        "display-3xl": ["60px", { lineHeight: "72px", letterSpacing: "-0.02em" }],
        "display-2xl": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em" }],
        "display-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em" }],
        "display-md": ["32px", { lineHeight: "40px" }],
        "display-sm": ["28px", { lineHeight: "38px" }],
        "display-xs": ["24px", { lineHeight: "36px" }],
        "text-xl": ["20px", { lineHeight: "34px" }],
        "text-lg": ["18px", { lineHeight: "32px" }],
        "text-md": ["16px", { lineHeight: "30px" }],
        "text-sm": ["14px", { lineHeight: "28px" }],
        "text-xs": ["12px", { lineHeight: "24px" }],
      },
      spacing: {
        "spacing-none": "0px",
        "spacing-xxs": "2px",
        "spacing-xs": "4px",
        "spacing-sm": "6px",
        "spacing-md": "8px",
        "spacing-lg": "12px",
        "spacing-xl": "16px",
        "spacing-2xl": "20px",
        "spacing-3xl": "24px",
        "spacing-4xl": "32px",
        "spacing-5xl": "40px",
        "spacing-6xl": "48px",
        "spacing-7xl": "64px",
        "spacing-8xl": "80px",
        "spacing-9xl": "96px",
        "spacing-10xl": "128px",
        "spacing-11xl": "140px",
      },
      borderRadius: {
        "radius-none": "0px",
        "radius-xxs": "2px",
        "radius-xs": "4px",
        "radius-sm": "6px",
        "radius-md": "8px",
        "radius-lg": "10px",
        "radius-xl": "12px",
        "radius-2xl": "16px",
        "radius-3xl": "20px",
        "radius-4xl": "24px",
        "radius-full": "9999px",
      },
    },
  },
  plugins: [],
};

export default config;